FROM zkf1317/opencv:4.10.0-cu118-py38-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive
ARG ONNXRUNTIME_VERSION=1.19.2

# apt install
RUN apt-get update && apt-get upgrade -y && \
    # Install build tools, build dependencies and python
    apt-get install -y \
	    python3-pip \
        build-essential \
        cmake \
        git \
        wget \
        unzip \
        yasm \
        pkg-config \
        ## Python
        python3-dev \
        python3-numpy \
    && rm -rf /var/lib/apt/lists/*

# onnxruntime
RUN pip install --upgrade pip
RUN cp /usr/local/bin/pip3.8 /usr/bin/pip
RUN pip install onnxruntime-gpu==${ONNXRUNTIME_VERSION} --extra-index-url \
    https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-11/pypi/simple
RUN pip install Pillow gradio shapely urllib3 chardet
